/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.User;

import Business.EcoSystem;

import Business.UserAccountManagement.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import Business.WorkQueue.EmergencyRequestDirectory;
import Business.User.User;
import Utility.MapCoordinates;
import Utility.Notification;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajesh
 */
public class EmergencyReport extends javax.swing.JPanel {

    EcoSystem system;
    JPanel rightSidePanel;
    MapCoordinates locationPoint;
    JPanel container;
    /**
     * Creates new form Emergency Report
     *
     * @param system
     * @param rightSidePanel
     */


   UserAccount userAcc;
    public EmergencyReport(JPanel container,EcoSystem system,UserAccount userAcc) {
        initComponents();
        this.rightSidePanel=container;
        this.system=system;
        this.userAcc=userAcc;
        User a=(User)userAcc;
        firstNameField.setText(a.getFirstName());
        lastNameField.setText(a.getLastName());

        displayTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergency = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        reportButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emergencyBox = new javax.swing.JComboBox<>();
        locationInputField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Report Emergency");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 31, -1, -1));

        tblEmergency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Location", "Status", "Response"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmergency);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 580, 520));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportButton.setBackground(new java.awt.Color(51, 51, 255));
        reportButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        reportButton.setForeground(new java.awt.Color(255, 255, 255));
        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        jPanel7.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 140, 30));

        cancelButton.setBackground(new java.awt.Color(255, 55, 95));
        cancelButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel7.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 160, 30));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel2.setText("Enter Details");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 50));

        firstNameLabel.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(73, 84, 90));
        firstNameLabel.setText("First Name");
        jPanel7.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 220, -1));

        lastNameField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 350, 30));

        lastNameLabel.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(73, 84, 90));
        lastNameLabel.setText("Last Name");
        jPanel7.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, -1));

        firstNameField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, 30));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Emergency");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, -1));

        emergencyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance", "Fire", "Maintenance" }));
        jPanel7.add(emergencyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 350, 30));

        locationInputField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(locationInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 350, 30));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("Location");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 220, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 450, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        reportEmergency();

    }//GEN-LAST:event_reportButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:

        cancelEmergency();

    }//GEN-LAST:event_cancelButtonActionPerformed

        public void populateLongituteLatitude(MapCoordinates locationPoint) {
        this.locationPoint = locationPoint;
        locationInputField.setText(locationPoint.getLatitudeCoordinate()+ ", " + locationPoint.getLongitudeCoordinate());   
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> emergencyBox;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField locationInputField;
    private javax.swing.JButton reportButton;
    private javax.swing.JTable tblEmergency;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        
        EmergencyRequestDirectory directory = system.getEmergencyRequestDirectory();
        List<EmergencyRequest> emergencyDir = directory.getEmergencyUserList();
        int l = emergencyDir.size();
        for (int i = 0; i < l; i++) {
            EmergencyRequest reqEmer = emergencyDir.get(i);
            if (userAcc.getUsername().matches(reqEmer.getUserId())) {
                DefaultTableModel table = (DefaultTableModel) tblEmergency.getModel();
                String r1 = String.valueOf(reqEmer.getId());
                String r2[] = {r1, reqEmer.getEmergency(), reqEmer.getLocation(), reqEmer.getStatus(), reqEmer.getResponse()};
                table.addRow(r2);
            }
        }

    }

    private void reportEmergency() {

        if (!locationInputField.getText().isEmpty()) {
            EmergencyRequest emergency = new EmergencyRequest();
            User user = (User) userAcc;
            int x = 1 + (int) (Math.random() * 100);
            emergency.setId(x);
            emergency.setName(user.getFirstName());
            emergency.setUserId(user.getUserId());
            emergency.setEmergency(emergencyBox.getSelectedItem().toString());
            emergency.setLocation(locationInputField.getText());
            emergency.setStatus("In Progress");
            emergency.setResponse("No Response");
            EmergencyRequestDirectory emergencyDirectory = system.getEmergencyRequestDirectory();
            emergencyDirectory.addEmergencyUser(emergency);
            String emailId = user.getEmail();
            String subject = "Emergency request has been raised";
            String content = "Emergency report is reported to the nearest Control Room.\n Emergency Response Team will be responding to the emergency immediately";
            sendmail(emailId, subject, content);
            tblEmergency.setModel(new DefaultTableModel(null, new String[]{"ID", "Emergency", "Location", "Status", "Response"}));
            displayTable();
            JOptionPane.showMessageDialog(null, "Reported Emergency Successfully!!!");
        } else {

            JOptionPane.showMessageDialog(null, "Please Enter the location for Emergency Services!");
        }
    }

    public void sendmail(String emailId, String subject, String content) {
        Notification notification = new Notification();
        String toEmail = emailId;
        String emailSubject = subject;
        String emailContent = content;
        notification.sendMail(toEmail, emailSubject, emailContent);
    }


    
    private void cancelEmergency() {
        
        User user = (User) userAcc;
        DefaultTableModel table = (DefaultTableModel) tblEmergency.getModel();
        int selectedRow = tblEmergency.getSelectedRow();
        if (selectedRow >= 0) {
            int sRow = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());
            EmergencyRequestDirectory emergencyDir = system.getEmergencyRequestDirectory();
            List<EmergencyRequest> emergencyList = emergencyDir.getEmergencyUserList();
            int l = emergencyList.size();
            for (int i = 0; i < l; i++) {
                EmergencyRequest emergencyRequest = emergencyList.get(i);
                if (sRow == emergencyRequest.getId()) {
                    if (emergencyRequest.getStatus().matches("In Progress")) {
                        String emailId = user.getEmail();
                        emergencyRequest.setStatus("Closed");
                        String subject = "Emergency request closed";
                        String content = "Emergency request ticket has been moved to closed status.";
                        sendmail(emailId, subject, content);
                        JOptionPane.showMessageDialog(null, "Case Closed");

                    } else if (emergencyRequest.getStatus().matches("Closed")) {
                        JOptionPane.showMessageDialog(null, "Your Emergency Case is Closed successfully!!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Reported as false Alarm!!");
                    }
                }

            }
            tblEmergency.setModel(new DefaultTableModel(null, new String[]{"ID", "Emergency", "Location", "Status", "Response"}));
            displayTable();
        } else {
            JOptionPane.showMessageDialog(null, "Select A Row!!");

        }

    }
}
