/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SysManager;

import Business.DatabaseUtil.DB4OUtil;
import Business.EcoSystem;
import Utility.MapCoordinates;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author rajesh
 */
public class POCEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmergencyEnterprises
     */
    private final EcoSystem system;
    private final JPanel container;
    MapCoordinates locationPoint;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    Timer timer;
    
    private void Time() {
                ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date= new Date();
                DateFormat timeFormat =  new SimpleDateFormat("HH:mm a");
                String time = timeFormat.format(date);
                timeLabel.setText(time);
            }
        };
        timer = new Timer(100, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }
    
    
    public POCEnterpriseJPanel(EcoSystem system, JPanel container) {
        initComponents();
        this.system = system;
        this.container = container;
        Time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        goBackButton = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ambulancePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        securityservicePanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        utilityservice = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        rightSidePanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1040, 190, 30));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        goBackButton.setBackground(new java.awt.Color(255, 255, 255));
        goBackButton.setPreferredSize(new java.awt.Dimension(100, 48));
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goBackButtonMousePressed(evt);
            }
        });
        goBackButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/exit.png"))); // NOI18N
        goBackButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, -1));

        jLabel22.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(115, 120, 128));
        jLabel22.setText("Return");
        goBackButton.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel2.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 290, 60));

        ambulancePanel.setBackground(new java.awt.Color(255, 255, 255));
        ambulancePanel.setPreferredSize(new java.awt.Dimension(100, 48));
        ambulancePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ambulancePanelMousePressed(evt);
            }
        });
        ambulancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 120, 128));
        jLabel6.setText("Ambulance");
        ambulancePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/ambul.png"))); // NOI18N
        ambulancePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, -1));

        jPanel2.add(ambulancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 60));

        securityservicePanel.setBackground(new java.awt.Color(255, 255, 255));
        securityservicePanel.setPreferredSize(new java.awt.Dimension(100, 48));
        securityservicePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                securityservicePanelMousePressed(evt);
            }
        });
        securityservicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/police.png"))); // NOI18N
        securityservicePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, -1));

        jLabel26.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(115, 120, 128));
        jLabel26.setText("Security Service");
        securityservicePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel2.add(securityservicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 60));

        utilityservice.setBackground(new java.awt.Color(255, 255, 255));
        utilityservice.setPreferredSize(new java.awt.Dimension(100, 48));
        utilityservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                utilityserviceMousePressed(evt);
            }
        });
        utilityservice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(115, 120, 128));
        jLabel24.setText("Utility Service");
        utilityservice.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/maintenancelogo.png"))); // NOI18N
        utilityservice.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 30));

        jPanel2.add(utilityservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 733, 290, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/RentalMain.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, 900));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setText("Point of Contact");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, -1));

        jLabel1.setForeground(new java.awt.Color(152, 151, 151));
        jLabel1.setText("Manage everything related to POC Enterprise");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        timeLabel.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        timeLabel.setText("3:45 PM");
        jPanel6.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 190, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1170, 90));

        rightSidePanel.setBackground(new java.awt.Color(250, 249, 251));
        rightSidePanel.setLayout(new java.awt.CardLayout());
        jPanel1.add(rightSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 1630, 810));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMousePressed
        // TODO add your handling code here:
        goBackButton.setBackground(new Color(213,230,249));
        
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_goBackButtonMousePressed

    private void ambulancePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambulancePanelMousePressed
        // TODO add your handling code here
        manageEmergencyEnterpriseAmbulance();
        
    }//GEN-LAST:event_ambulancePanelMousePressed

    private void manageEmergencyEnterpriseAmbulance() {
        ambulancePanel.setBackground(new Color(213,230,249));
        utilityservice.setBackground(new Color(255,255,255));
        securityservicePanel.setBackground(new Color(255,255,255));
        AmbulanceRegistration amb =new AmbulanceRegistration(system,container);
        rightSidePanel.add(amb);
        CardLayout layout = (CardLayout) rightSidePanel.getLayout();
        layout.next(rightSidePanel);
    }
    
    private void utilityserviceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilityserviceMousePressed
        // TODO add your handling code here:
        manageEmergencyEnterprisePolice();
    }//GEN-LAST:event_utilityserviceMousePressed

    private void manageEmergencyEnterprisePolice() {
        ambulancePanel.setBackground(new Color(255,255,255));
        utilityservice.setBackground(new Color(213,230,249));
        securityservicePanel.setBackground(new Color(255,255,255));
        
        UtilityServiceRegistration amb =new UtilityServiceRegistration(system,rightSidePanel, locationPoint);
        rightSidePanel.add(amb);
        CardLayout layout = (CardLayout) rightSidePanel.getLayout();
        layout.next(rightSidePanel);
    }
    private void securityservicePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityservicePanelMousePressed
        // TODO add your handling code here:
        manageEmergencyEnterpriseFire();
    }//GEN-LAST:event_securityservicePanelMousePressed

    private void manageEmergencyEnterpriseFire() {
        ambulancePanel.setBackground(new Color(255,255,255));
        utilityservice.setBackground(new Color(255,255,255));
        securityservicePanel.setBackground(new Color(213,230,249));
        SecurityServiceRegistration amb =new SecurityServiceRegistration(system,rightSidePanel, locationPoint);
        rightSidePanel.add(amb);
        CardLayout layout = (CardLayout) rightSidePanel.getLayout();
        layout.next(rightSidePanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ambulancePanel;
    private javax.swing.JPanel goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JPanel securityservicePanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel utilityservice;
    // End of variables declaration//GEN-END:variables
}
