/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SysManager;

import Business.DatabaseUtil.DB4OUtil;
import Business.EcoSystem;
import UserInterface.PropertyDevelopment.PropertyDevelopmentJPanel;
import UserInterface.UserLogin;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author rajesh
 */

public class SysManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysManagerWorkAreaJPanel
     */
    JPanel container;
    EcoSystem ecosystem;

    public SysManagerWorkAreaJPanel(JPanel container,EcoSystem ecosystem) {
        initComponents();
       // ecosystem = dB4OUtil.retrieveSystem();
        this.setSize(1920, 1080);
        this.container=container;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        builderButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        emergencyButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        homeEssentialsButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        governmentButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        agentButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        exitLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 192, 193));
        jLabel2.setText("Easily manage your enteprise in this section");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel12.setText("Builder Enterprise");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(106, 110, 133));
        jLabel13.setText("house availability and new listings");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, 30));

        jLabel14.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(106, 110, 133));
        jLabel14.setText("Place where you can manage Builder's");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 30));

        builderButton.setBackground(new java.awt.Color(51, 51, 255));
        builderButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        builderButton.setForeground(new java.awt.Color(255, 255, 255));
        builderButton.setText("Manage");
        builderButton.setBorder(null);
        builderButton.setFocusPainted(false);
        builderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                builderButtonActionPerformed(evt);
            }
        });
        jPanel4.add(builderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/Builderenter.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 330, 240));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel20.setText("Tenant POC Enterprise");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(106, 110, 133));
        jLabel21.setText("Security, medical and personal emergency");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 30));

        jLabel22.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(106, 110, 133));
        jLabel22.setText("Place where you can manage emergencies");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 30));

        emergencyButton.setBackground(new java.awt.Color(51, 51, 255));
        emergencyButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        emergencyButton.setForeground(new java.awt.Color(255, 255, 255));
        emergencyButton.setText("Manage");
        emergencyButton.setBorder(null);
        emergencyButton.setFocusPainted(false);
        emergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyButtonActionPerformed(evt);
            }
        });
        jPanel6.add(emergencyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/POC.png"))); // NOI18N
        jLabel25.setText("jLabel23");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 70));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 350, 260));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel4.setText("Home Essential Enterprise");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        jLabel5.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 110, 133));
        jLabel5.setText("Tenant essentials home essential");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, 30));

        jLabel6.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 110, 133));
        jLabel6.setText("Place where you can manage Home Essential");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, 30));

        homeEssentialsButton.setBackground(new java.awt.Color(51, 51, 255));
        homeEssentialsButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        homeEssentialsButton.setForeground(new java.awt.Color(255, 255, 255));
        homeEssentialsButton.setText("Manage");
        homeEssentialsButton.setBorder(null);
        homeEssentialsButton.setFocusPainted(false);
        homeEssentialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeEssentialsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(homeEssentialsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/Marketplace.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 330, 240));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel16.setText("Property Dev Board Enterprise");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(106, 110, 133));
        jLabel17.setText("See tenant requirement trends");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, 30));

        jLabel18.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(106, 110, 133));
        jLabel18.setText("Place where you can manage housing board");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 30));

        governmentButton.setBackground(new java.awt.Color(51, 51, 255));
        governmentButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        governmentButton.setForeground(new java.awt.Color(255, 255, 255));
        governmentButton.setText("Manage");
        governmentButton.setBorder(null);
        governmentButton.setFocusPainted(false);
        governmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governmentButtonActionPerformed(evt);
            }
        });
        jPanel5.add(governmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/Husindev.png"))); // NOI18N
        jLabel27.setText("jLabel23");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 340, 260));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        jLabel8.setText("Agent Enterprise");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(106, 110, 133));
        jLabel9.setText("Rental agent for tenant housing");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 250, 30));

        jLabel10.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 110, 133));
        jLabel10.setText("Place where you can manage agent");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, 30));

        agentButton.setBackground(new java.awt.Color(51, 51, 255));
        agentButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        agentButton.setForeground(new java.awt.Color(255, 255, 255));
        agentButton.setText("Manage");
        agentButton.setBorder(null);
        agentButton.setFocusPainted(false);
        agentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(agentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/Agenterprise.png"))); // NOI18N
        jLabel24.setText("jLabel23");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 320, 240));

        exitLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Icons/exitbig.png"))); // NOI18N
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabel1MousePressed(evt);
            }
        });
        jPanel1.add(exitLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, 60, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MousePressed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_exitLabel1MousePressed

    private void agentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonActionPerformed
        // TODO add your handling code here:
        RentalAgencyEnterpriseJPanel ra = new RentalAgencyEnterpriseJPanel(ecosystem, container);
        container.add(ra);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_agentButtonActionPerformed

    private void homeEssentialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeEssentialsButtonActionPerformed
        // TODO add your handling code here:
        HomeEssentialsSysJPanel marketplaceEnterpriseJPanel = new HomeEssentialsSysJPanel(ecosystem, container);
        container.add(marketplaceEnterpriseJPanel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_homeEssentialsButtonActionPerformed

    private void builderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_builderButtonActionPerformed
        // TODO add your handling code here:
        BuilderEnterpriseJPanel builderEnterpriseJPanel = new BuilderEnterpriseJPanel(ecosystem, container);
        container.add(builderEnterpriseJPanel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_builderButtonActionPerformed

    private void emergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyButtonActionPerformed
        // TODO add your handling code here:
        POCEnterpriseJPanel pOCEnterpriseJPanel = new POCEnterpriseJPanel(ecosystem, container);
        container.add(pOCEnterpriseJPanel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_emergencyButtonActionPerformed

    private void governmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governmentButtonActionPerformed
        // TODO add your handling code here:
        PropertyDevBoardEnterpirse boardEnterpirse = new PropertyDevBoardEnterpirse(ecosystem, container);
        container.add(boardEnterpirse);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_governmentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agentButton;
    private javax.swing.JButton builderButton;
    private javax.swing.JButton emergencyButton;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JButton governmentButton;
    private javax.swing.JButton homeEssentialsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
